apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management-backend
  template:
    metadata:
      labels:
        app: inventory-management-backend
    spec:
      containers:
        - name: backend
          image: docker.io/harishree11/inventory-management-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://harishreelakshmanakumar:1234567890@cluster0.qcqv7rh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management-frontend
  template:
    metadata:
      labels:
        app: inventory-management-frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/harishree11/inventory-management-frontend:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: inventory-management-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: inventory-management-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
