pipeline {     
    agent any      
    
    environment {         
        BACKEND_IMAGE_NAME  = "inventory-management-backend"         
        FRONTEND_IMAGE_NAME = "inventory-management-frontend"         
        IMAGE_TAG           = "latest"         
        DOCKER_REGISTRY     = "docker.io"         
        DOCKER_REPO         = "harishree11" 
        KUBECONFIG = "/home/hari/.kube/config"    
    }      

    stages {         
        stage('Checkout') {             
            steps {                 
                script {                     
                    git branch: 'main', url: 'https://github.com/harishreelakshmanakumar/react-devops.git'                 
                }             
            }         
        }          
        
        stage('Build Backend Image') {             
            steps {                 
                script {                     
                    dockerImageBackend = docker.build("${DOCKER_REPO}/${BACKEND_IMAGE_NAME}:${IMAGE_TAG}", "./React-Inventory-Management-System-main/backend")                 
                }             
            }         
        }          

        stage('Build Frontend Image') {             
            steps {                 
                script {                     
                    dockerImageFrontend = docker.build("${DOCKER_REPO}/${FRONTEND_IMAGE_NAME}:${IMAGE_TAG}", "./React-Inventory-Management-System-main/frontend")                 
                }             
            }         
        }          

        stage('Push Docker Images') {      
            steps {          
                script {              
                    sh 'docker login -u harishree11 -p "Hari@1104"'             
                    dockerImageBackend.push("${IMAGE_TAG}")              
                    dockerImageFrontend.push("${IMAGE_TAG}")          
                }      
            }  
        }            

       stage('Deploy to Minikube') {
    steps {
        script {
            sh 'kubectl apply -f deploy.yaml --kubeconfig=/home/hari/.kube/config --validate=false'
        }
    }
       }   
    }  // <-- Closing `stages {}` block here

    post {         
        always {             
            echo "Pipeline execution completed."         
        }     
    } 
}
