pipeline {
    agent any

    environment {
        BACKEND_IMAGE_NAME  = "inventory-management-backend"
        FRONTEND_IMAGE_NAME = "inventory-management-frontend"
        IMAGE_TAG           = "latest"
        DOCKER_REGISTRY     = "docker.io"
        DOCKER_REPO         = "harishree11"
        KUBECONFIG = "/var/lib/jenkins/.kube/config"  // Jenkins-owned path
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    git branch: 'main', url: 'https://github.com/harishreelakshmanakumar/react-devops.git'
                }
            }
        }

        stage('Build Backend Image') {
            steps {
                script {
                    dockerImageBackend = docker.build("${DOCKER_REPO}/${BACKEND_IMAGE_NAME}:${IMAGE_TAG}", "./React-Inventory-Management-System-main/Backend")
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                script {
                    dockerImageFrontend = docker.build("${DOCKER_REPO}/${FRONTEND_IMAGE_NAME}:${IMAGE_TAG}", "./React-Inventory-Management-System-main/Frontend")
                }
            }
        }

        stage('Push Docker Images') {
            steps {
                script {
                    sh 'docker login -u harishree11 -p "Hari@1104"'
                    dockerImageBackend.push("${IMAGE_TAG}")
                    dockerImageFrontend.push("${IMAGE_TAG}")
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                script {
                    sh 'kubectl apply -f deploy.yaml --kubeconfig=/var/lib/jenkins/.kube/config --validate=false'
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline execution completed."
        }
    }
}
